//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public interface IHealthEntity
{

	//damage the entity by amount.  Does no damage if the provided team is the same as the entity's.

	//The same damage source cannot damage the same entity multiple times in a frame.  Subsequent calls to Damage() will be ignored.
	//This is so that you don't have to worry about damaging multiple DamageableParts at the same time and multiplying damage.
	void Damage(string damagerTeam, DamageSource source, int amount);

	// Heal the entity by amount.
	void Heal(int amount);

	//If this is a sub-healthentity of another entity, return it
	//otherwise, return null
	//Can only be singly nested, so if GetParent returns a value, then the parent returned will not have a parent.
	IHealthEntity GetParent();

	// return true if the object is alive.
	bool IsAlive();

	//Gets the GameObject of the entity.  If the entity is a child, this returns the object of the parent.
	GameObject GetGameObject();
}


